# Learning GitHub Actions

`https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows`

`https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#filter-pattern-cheat-sheet`


name: first

on: push

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: date
  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: Get-Date
  job3:
    name: Third Job
    runs-on: macos-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: date
  job4:
    name: Fourth Job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: echo Hello, world!
